name: Publish
on:
  push:
    branches:
      - chore/deploy-s3
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - run: npm run bootstrap
    - run: npm run ci:test
    - run: npm run ci:build
    - name: Fucking publish
    - run: npm publish
      working-directory: ./packages/force-components
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}